"""Regenerate public/notebook/index.html from all published output_ledger rows.

Schedule: IntervalTrigger(hours=2)

Run manually:
    python -m agent.jobs.notebook_index
"""
import html
import os
import sqlite3
from datetime import datetime, timezone

_PROJECT_ROOT = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
)

from agent.jobs import tracked  # noqa: E402
from agent.scheduler import DB_PATH  # noqa: E402

_NOTEBOOK_DIR = os.path.join(_PROJECT_ROOT, "public", "notebook")
_INDEX_PATH = os.path.join(_NOTEBOOK_DIR, "index.html")

_INDEX_HEADER = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tealc Open Lab Notebook</title>
  <style>
    :root {{ --accent: #2563eb; --bg: #f8fafc; --border: #e2e8f0; --muted: #64748b; }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: system-ui, sans-serif; background: var(--bg); color: #1e293b; line-height: 1.6; }}
    header {{ background: var(--accent); color: #fff; padding: 1rem 2rem; }}
    header h1 {{ font-size: 1.3rem; font-weight: 700; }}
    main {{ max-width: 900px; margin: 2rem auto; padding: 0 1rem; }}
    .intro {{ color: var(--muted); margin-bottom: 1.5rem; font-size: .95rem; max-width: 680px; }}
    table {{ width: 100%; border-collapse: collapse; background: #fff;
             border: 1px solid var(--border); border-radius: .5rem; overflow: hidden; }}
    th {{ background: var(--accent); color: #fff; text-align: left;
          padding: .6rem 1rem; font-size: .8rem; text-transform: uppercase; letter-spacing: .05em; }}
    td {{ padding: .6rem 1rem; border-top: 1px solid var(--border); font-size: .9rem; vertical-align: top; }}
    tr:hover td {{ background: #f1f5f9; }}
    .kind-badge {{ display: inline-block; background: #dbeafe; color: #1d4ed8;
                   border-radius: 999px; padding: .1rem .55rem; font-size: .75rem; }}
    .score {{ font-weight: 600; color: #16a34a; }}
    a {{ color: var(--accent); text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    .empty {{ color: var(--muted); padding: 2rem; text-align: center; }}
    footer {{ text-align: center; color: var(--muted); font-size: .8rem; padding: 2rem; }}
  </style>
</head>
<body>
<header>
  <h1>Tealc Open Lab Notebook</h1>
</header>
<main>
  <p class="intro">
    This notebook is the full-transparency record of Tealc's autonomous research outputs.
    Every entry here shows the complete artifact body, model, provenance hashes, critic score,
    and estimated cost. The thesis: radical openness about AI-generated science earns more
    credibility than secrecy. Entries appear after a mandatory 24-hour embargo and explicit
    author approval. All artifacts default to <em>private</em>; nothing is published without
    the researcher's sign-off.
  </p>
  <p style="color:var(--muted);font-size:.85rem;margin-bottom:1rem;">
    Generated: {generated_at}  &nbsp;|&nbsp; {count} published entries
  </p>
"""

_INDEX_FOOTER = """</main>
<footer>Generated by Tealc</footer>
</body>
</html>
"""

_EMPTY_BODY = """  <div class="empty">No published artifacts yet.</div>
"""

_TABLE_HEADER = """  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Kind</th>
        <th>Date</th>
        <th>Critic</th>
        <th>Link</th>
      </tr>
    </thead>
    <tbody>
"""

_TABLE_ROW = (
    "      <tr>"
    "<td>{id}</td>"
    "<td><span class='kind-badge'>{kind}</span></td>"
    "<td>{date}</td>"
    "<td class='score'>{score}</td>"
    "<td><a href='{url}'>view</a></td>"
    "</tr>\n"
)

_TABLE_FOOTER = "    </tbody>\n  </table>\n"


@tracked("notebook_index")
def job() -> str:
    os.makedirs(_NOTEBOOK_DIR, exist_ok=True)
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.row_factory = sqlite3.Row

    rows = conn.execute(
        "SELECT id, kind, created_at, published_at, critic_score, public_url "
        "FROM output_ledger WHERE publish_state='published' "
        "ORDER BY published_at DESC"
    ).fetchall()
    conn.close()

    count = len(rows)
    parts: list[str] = [_INDEX_HEADER.format(generated_at=now_iso, count=count)]

    if not rows:
        parts.append(_EMPTY_BODY)
    else:
        parts.append(_TABLE_HEADER)
        for r in rows:
            score = r["critic_score"]
            score_str = str(score) if score is not None else "—"
            date_str = (r["published_at"] or r["created_at"] or "")[:10]
            parts.append(_TABLE_ROW.format(
                id    = r["id"],
                kind  = html.escape(r["kind"] or ""),
                date  = date_str,
                score = score_str,
                url   = html.escape(r["public_url"] or f"/notebook/{r['id']}.html"),
            ))
        parts.append(_TABLE_FOOTER)

    parts.append(_INDEX_FOOTER)

    with open(_INDEX_PATH, "w", encoding="utf-8") as f:
        f.write("".join(parts))

    return f"notebook_index: regenerated index with {count} entries"


if __name__ == "__main__":
    print(job())
